train_pressure:
- '1'
- '1'
- '1'
- '1'
- '1'
- '1'
- '1'
- '1'
train_sample:
- '374'
- '374'
- '374'
- '374'
- '374'
- '374'
- '374'
- '57'
train_size:
- '256'
- '256'
- '256'
- '256'
- '256'
- '256'
- '256'
- '256'
train_subsample:
- '42'
- '57'
- '02'
- '03'
- '04'
- '05'
- '06'
- '01'
val_pressure:
- '1'
- '1'
- '1'
- '1'
val_sample:
- '374'
- '374'
- '374'
- '57'
val_size:
- '256'
- '256'
- '256'
- '256'
val_subsample:
- '44'
- '00'
- '18'
- '04'
x_array:
- bin
x_xform:
- None
y_array:
- phi
y_xform:
- None
