train_pressure:
- '1'
- '1'
- '1'
- '1'
- '1'
- '1'
- '1'
- '1'
- '1'
- '1'
- '1'
- '1'
- '1'
- '1'
- '1'
- '1'
- '1'
- '1'
- '1'
- '1'
- '1'
- '1'
- '1'
- '1'
- '1'
- '1'
- '1'
- '1'
- '1'
- '1'
- '1'
- '1'
- '1'
- '1'
- '1'
- '1'
- '1'
- '1'
- '1'
train_sample:
- '374'
- '374'
- '374'
- '374'
- '374'
- '374'
- '374'
- '374'
- '374'
- '374'
- '374'
- '374'
- '374'
- '374'
- '374'
- '374'
- '374'
- '374'
- '374'
- '374'
- '374'
- '374'
- '374'
- '374'
- '374'
- '57'
- '374'
- '374'
- '374'
- '374'
- '374'
- '374'
- '374'
- '57'
- '57'
- '374'
- '374'
- '374'
- '374'
train_size:
- '256'
- '256'
- '256'
- '256'
- '256'
- '256'
- '256'
- '256'
- '256'
- '256'
- '256'
- '256'
- '256'
- '256'
- '256'
- '256'
- '256'
- '256'
- '256'
- '256'
- '256'
- '256'
- '256'
- '256'
- '256'
- '256'
- '256'
- '256'
- '256'
- '256'
- '256'
- '256'
- '256'
- '256'
- '256'
- '256'
- '256'
- '256'
- '256'
train_subsample:
- '04'
- '49'
- '12'
- '40'
- '59'
- '27'
- '01'
- '54'
- '25'
- '38'
- '58'
- '44'
- '03'
- '34'
- '31'
- '29'
- 09
- '43'
- '18'
- '41'
- '28'
- '17'
- '13'
- '36'
- '48'
- '04'
- '53'
- '55'
- '56'
- '06'
- '24'
- '60'
- '16'
- '01'
- '06'
- '57'
- '50'
- '11'
- '32'
val_pressure:
- '1'
- '1'
- '1'
- '1'
- '1'
- '1'
- '1'
- '1'
- '1'
- '1'
- '1'
- '1'
- '1'
- '1'
- '1'
- '1'
- '1'
- '1'
- '1'

val_sample:
- '374'
- '374'
- '374'
- '374'
- '374'
- '374'
- '374'
- '374'
- '374'
- '374'
- '374'
- '374'
- '374'
- '374'
- '374'
- '374'
- '374'
- '57'
- '57'
val_size:
- '256'
- '256'
- '256'
- '256'
- '256'
- '256'
- '256'
- '256'
- '256'
- '256'
- '256'
- '256'
- '256'
- '256'
- '256'
- '256'
- '256'
- '256'
- '256'
val_subsample:
- '00'
- '02'
- '14'
- '19'
- '20'
- '21'
- '23'
- '26'
- '30'
- '33'
- '35'
- '37'
- '39'
- '42'
- '45'
- '52'
- '61'
- '05'
- '03'
x_array:
- 'bin'
y_array:
- 'phi'
x_xform:
- None
y_xform:
- None