---

num_rounds: 10
num_clients: 100
batch_size: 1
num_clients_per_round_fit: 2
num_clients_per_round_eval: 2

config_fit:
  lr: 1.e-5
  local_epochs: 100

defaults:
  - model: msnet
  - strategy: fedavg  # points to conf/strategy/fedavg.yaml