---

num_rounds: 10
round_timeout: !!null
num_clients: 2
batch_size: 1
num_clients_per_round_fit: 2
num_clients_per_round_eval: 2
device: cpu

train_input_file: ???
test_input_file: test_data.yml
data_loc: ./training_data
dp:
  use: false
  target_delta: 1.e-5
  noise_multiplier: 0.4
  max_grad_norm: 1.2


config_fit:
  lr: 1.e-5
  local_epochs: 1

defaults:
  - model: msnet
  - strategy: fedavg  # points to conf/strategy/fedavg.yaml
  - optimizer: adam.yaml # points to conf/optimizer/adam.yaml